apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-wake-prod
  namespace: server-wake-prod
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50M
  storageClassName: nfs-client
